pipeline:
  name: githubFeaturepip
  identifier: githubFeaturepip
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: a34
                  identifier: a34
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 'hi'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
