pipeline:
  name: NewRemote13Sept
  identifier: NewRemote13Sept
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: A2
                  identifier: A2
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression 321
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
  connectorRef: account.github_app_token
  storeType: REMOTE
  filePath: .harness/NewRemote13Sept.yaml
