pipeline:
  name: NonDefaultPipelIneBr
  identifier: NonDefaultPipelIneBr
  template:
    templateRef: org.RemotePipeTemplate
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: acxc
            template:
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: A21
                          type: HarnessApproval
                          spec:
                            approvers:
                              userGroups: <+input>
  tags: {}
  projectIdentifier: AmitTest
  orgIdentifier: default
