pipeline:
  name: RemoteGithub app
  identifier: RemoteGithub_app
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A2
        identifier: A2
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: S3
                  identifier: S3
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
